name: Deploy Health DogTag

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Puxar o código do repositório
      - name: Checkout site-health
        uses: actions/checkout@v4

      # Passo 2: Preparar pasta de deploy sem o README.md
      - name: Preparar pasta de deploy
        run: |
          mkdir deploy
          rsync -av --exclude 'README.md' ./ deploy/

      # Passo 3: Deploy usando peaceiris/actions-gh-pages
      - name: Deploy para /tools/maskDisplay
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: le314u/le314u.github.io
          publish_branch: prod
          publish_dir: deploy
          destination_dir: health
